context:
  version: "2.10.0"

package:
  name: tauri
  version: ${{ version }}

source:
  url: https://github.com/tauri-apps/tauri/archive/tauri-cli-v${{ version }}.tar.gz
  sha256: af537feacfc2d148cf5ce8f5fc53cb2571a310d89ec428cb4d403b1690676384

build:
  number: 0
  skip: ppc64le

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - cargo-tauri --help

about:
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE_MIT
    - LICENSE_APACHE-2.0
    - THIRDPARTY.yml
  summary: Build smaller, faster, and more secure desktop applications with a web frontend.
  homepage: https://github.com/tauri-apps/tauri
  repository: https://github.com/tauri-apps/tauri

extra:
  recipe-maintainers:
    - danielnachun
