context:
  version: "2.5.0"

package:
  name: tauri
  version: ${{ version }}

source:
  url: https://github.com/tauri-apps/tauri/archive/tauri-cli-v${{ version }}.tar.gz
  sha256: 63545497b0a54380cd270fafe94e813c08d4f49685246fca413ba56ca76ac647

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - cargo-tauri --help

about:
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE_MIT
    - LICENSE_APACHE-2.0
    - THIRDPARTY.yml
  summary: Build smaller, faster, and more secure desktop applications with a web frontend.
  homepage: https://github.com/tauri-apps/tauri
  repository: https://github.com/tauri-apps/tauri

extra:
  recipe-maintainers:
    - danielnachun
